name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Publish
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build release binaries
        run: zig build -Doptimize=ReleaseFast

      - name: Run tests
        run: zig build test

      - name: Prepare artifacts
        run: |
          ARCH=$(uname -m)
          OS=${RUNNER_OS:-unknown}
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME}"
          else
            VERSION="${GITHUB_SHA}"
          fi
          echo "ARCH=$ARCH" >> "$GITHUB_ENV"
          echo "OS=$OS" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          mkdir -p dist
          cp zig-out/bin/zblock dist/
          cp zig-out/bin/zblockd dist/
          (cd dist && tar -czf "zblock-${VERSION}-${OS}-${ARCH}.tar.gz" zblock zblockd)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: zblock-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
          path: dist/zblock-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz

      - name: Publish release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/zblock-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
